access_key = "XX"
secret_key = "YY"
instance_count=2
environment = "Bilal-Demo"
health_check_type = "EC2"
health_check_healthy_threshold = 2
health_check_unhealthy_threshold = 2
health_check_target = "HTTP:8085/"
health_check_interval = 15
health_check_timeout = 3
